baseURL = 'https://jmoran2611.github.io/'
languageCode = 'en-us'
title = 'Javier Moran-Fraile'
theme = ['hugo-video','personal-web']
copyright="© Javier Moran Fraile"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hello there, I'm Javier Morán Fraile"
  sub = "Post doctoral researcher in astrophysics based in Heidelberg, Germany"

[params.main]
  latestPublishHeader = "My Latest Project"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['publications'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404
  rendererSafe = false # set to true if wish to remove the unsafe renderer setting below (recommended). Titles will not be run through markdownify

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  videos = "videos"

[params.sidebar]
  backgroundImage = '' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "images/profile-pic.png" # - default "/images/edna-west.jpg"
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/jmoran2611"
#  twitter = "https://twitter.com/"
  linkedin = "https://www.linkedin.com/in/javier-mor%C3%A1n-fraile-83583915b"
#  medium = "https://medium.com/"
#  codepen = "https://codepen.io/"
#  facebook = "https://www.facebook.com/"
#  youtube = "https://www.youtube.com/"
  instagram = "https://www.instagram.com/jmoran2611"
#  gitlab = "https://gitlab.com/"
#  keybase = "https://keybase.io/"

[params.contact]
  email = "javier.moranfraile@h-its.org"
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "publications"
  name = "Publications"
  title = "Publications"
  url = "/publications/"
  weight = -110

[[menu.main]]
  identifier = "blog"
  name = "Post"
  title = "Blog section"
  url = "/posts/"
  weight = -100

[[menu.main]]
  identifier = "videos"
  name = "Videos"
  title = "Videos"
  url = "/videos/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
